version: "3.8"

services:
  # Servicio de MariaDB sin contraseña
  db:
    image: mariadb:10.5
    container_name: mariadb_db
    ports:
      - "3306:3306"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: euno
      MARIADB_USER: root
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mariadbnet

volumes:
  mariadb_data:
    driver: local

networks:
  mariadbnet:
    driver: bridge

